image: node:14.19.0

cache:
  paths:
    - node_modules/
push_to_production:
  before_script:
    - echo "CI_PIPELINE_SOURCE = $CI_PIPELINE_SOURCE"
    - npm install
    - echo "TRIGGER_PAYLOAD=$TRIGGER_PAYLOAD" >> ".env"
  script:
    - npm run publisher -y
