image: node:14.19.0

cache:
  paths:
    - node_modules/
test_async:
  before_script:
    - pwd
    - ls -a
    # - npm install
    - echo "TRIGGER_PAYLOAD=$TRIGGER_PAYLOAD" >> ".env"
    - echo "CI_PIPELINE_SOURCE=$CI_PIPELINE_SOURCE" >> ".env"
  script:
    - pwd
    - ls -a
    - cat ".env"
    - npm run publisher -y
